language: python

python:
  - 3.7
  - 3.8

env:
  - FLASK=1.1.2

cache:
  directories:
  - "$HOME/virtualenv"

install:
  - pip install -r requirements.txt

script:
  - pytest tests
  - flake8 app/ tests/

